plotty: rename protobuf directory
Protobuf in python3.12 uses "proto/" dir, which collides with
our own.

Also removed use in postfilter.py.

Tested:

Before:
```
>>> from proto import plotty_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'plotty_pb2' from 'proto' (/usr/local/lib/python3.12/site-packages/proto/__init__.py)
```

After:
```
>>> from protobuf import plotty_pb2
>>>
```