plotty: plot: rename "filter" as "prefilter"
We will have 2x filters:
* prefilter: filter used to decide which lines in the data input (csv) to
  ignore
* postfilter: filter used to post-process the y-axis data (e.g. replacing
  a noisy distribution with a rolling average).

This patch makes sure we always use "prefilter" to refer to the prefilter.

Tested:

```
$ ./plotty-plot_unittest.py
...running basic
E...running basic
/usr/lib64/python3.10/string.py:114: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 mode='w' encoding='ISO-8859-15'>
  return str(mapping[named])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
...running basic (no x col)
...running basic (named xcol)
...running basic (named ycol)
...running basic (named xcol and ycol)
...running twinx
....running basic
...running [x|y]col == -1 implies line number
...running xcol2
...running ycol2, swapping separators
...running ydelta
...running ycumulative
...running prefilter
...running prefilter arithmetic
...running prefilter multiple (and)
...running prefilter multiple (or)
...running prefilter multiple (and/or)
...running histogram
...running histogram bins 1
...running histogram bins 2
...running histogram pdf 1
...running histogram pdf 2
...running histogram cdf 1
...running histogram cdf 2
...running histogram sigma 1
...running histogram sigma 2
...running histogram sigma 2b
.
======================================================================
ERROR: testBatchProcessData (__main__.MyTest)
Simplest batch_process_data test.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chemag/proj/plotty/./plotty-plot_unittest.py", line 552, in testBatchProcessData
    infile_list = plotty_plot.batch_process_data(
TypeError: batch_process_data() missing 1 required positional argument: 'header'

----------------------------------------------------------------------
Ran 3 tests in 0.050s

FAILED (errors=1)
```